// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkonQ10vojtnJuCXMDCzEFOAu0BZAk8o',
    appId: '1:911262943055:web:ad95d2a2c5115460e7a73a',
    messagingSenderId: '911262943055',
    projectId: 'gps-proof-share',
    authDomain: 'gps-proof-share.firebaseapp.com',
    storageBucket: 'gps-proof-share.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuBsfas3AkPOd0a5oGAbSQbBqHcrSM9k',
    appId: '1:911262943055:android:ae79ffdc78a9f3c5e7a73a',
    messagingSenderId: '911262943055',
    projectId: 'gps-proof-share',
    storageBucket: 'gps-proof-share.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdKwzLZMIfNeamqetsAOMzpUXKHs0Zfs',
    appId: '1:911262943055:ios:a39794f7553ccc8be7a73a',
    messagingSenderId: '911262943055',
    projectId: 'gps-proof-share',
    storageBucket: 'gps-proof-share.firebasestorage.app',
    iosBundleId: 'com.example.gpsSpoofShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdKwzLZMIfNeamqetsAOMzpUXKHs0Zfs',
    appId: '1:911262943055:ios:a39794f7553ccc8be7a73a',
    messagingSenderId: '911262943055',
    projectId: 'gps-proof-share',
    storageBucket: 'gps-proof-share.firebasestorage.app',
    iosBundleId: 'com.example.gpsSpoofShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIkonQ10vojtnJuCXMDCzEFOAu0BZAk8o',
    appId: '1:911262943055:web:a5b6e26c2f3de71fe7a73a',
    messagingSenderId: '911262943055',
    projectId: 'gps-proof-share',
    authDomain: 'gps-proof-share.firebaseapp.com',
    storageBucket: 'gps-proof-share.firebasestorage.app',
  );
}
