import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'app/routes/app_pages.dart';
import 'app/core/theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");

  // Send API key to iOS Native before UI loads
  if (!kIsWeb && Platform.isIOS) {
    const channel = MethodChannel('com.example.gpsspoofshare/native_bridge');
    try {
      await channel.invokeMethod('setGoogleMapsApiKey', {
        'apiKey': dotenv.env['GOOGLE_MAPS_API_KEY'] ?? '',
      });
    } catch (e) {
      debugPrint("Failed to set API Key on iOS: $e");
    }
  }

  // Initialize Firebase with platform-specific options
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase initialization error: $e");
  }

  runApp(
    GetMaterialApp(
      title: "GPS Spoof Share",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      debugShowCheckedModeBanner: false,
    ),
  );
}
